In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [13]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [17]:
a = np.array([1,3,5,6,7,9,11])
a

array([ 1,  3,  5,  6,  7,  9, 11])

In [19]:
a[2]

np.int64(5)

In [20]:
a[2] = 10

In [21]:
a

array([ 1,  3, 10,  6,  7,  9, 11])

In [22]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.arange(3, 11)

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [25]:
np.linspace(0,2,11)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

# Two or Multi Dimentional Arrays

In [27]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
n = np.array([[1,2,3],
         [4,5,6],
          [7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
n[0,1]

np.int64(2)

In [33]:
n[0,1] = 20

In [34]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [35]:
n[0]

array([ 1, 20,  3])

In [36]:
n[2] = [6,6,6]

In [37]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 6,  6,  6]])

In [38]:
n[:,1]

array([20,  5,  6])

In [40]:
 n[:,2] = [20,30,40]

In [41]:
n

array([[ 1, 20, 20],
       [ 4,  5, 30],
       [ 6,  6, 40]])

# Randomly Generated Arrays

In [50]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [44]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [45]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [47]:
np.random.seed(2)
np.random.randint(low=5, high =77, size=(7,6))

array([[45, 20, 27, 48, 12, 39],
       [54, 52, 68, 36, 25, 42],
       [44, 72,  9, 47, 56, 43],
       [38, 63, 72, 74, 73, 51],
       [75, 36, 71, 57, 55,  9],
       [68, 54, 44, 51, 13, 55],
       [20, 13, 22, 27, 62, 67]])

# Elemet- wise Operations

In [49]:
b=np.arange(5)
b

array([0, 1, 2, 3, 4])

In [51]:
b+3

array([3, 4, 5, 6, 7])

In [52]:
b*6

array([ 0,  6, 12, 18, 24])

In [60]:
c=(10 + (b*2))**2/100

In [61]:
b+c

array([1.  , 2.44, 3.96, 5.56, 7.24])

# Comparison Operators

In [58]:
b

array([0, 1, 2, 3, 4])

In [63]:
c

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [59]:
b>=3

array([False, False, False,  True,  True])

In [62]:
b>c

array([False, False,  True,  True,  True])

In [64]:
b[b>c]

array([2, 3, 4])

# Summarizing Operations

In [65]:
b

array([0, 1, 2, 3, 4])

In [66]:
b.sum()

np.int64(10)

In [67]:
b.mean()

np.float64(2.0)

In [69]:
b.std()

np.float64(1.4142135623730951)

In [70]:
n

array([[ 1, 20, 20],
       [ 4,  5, 30],
       [ 6,  6, 40]])

In [71]:
n.sum()

np.int64(132)

In [72]:
n.min()

np.int64(1)

In [73]:
n.max()

np.int64(40)